/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "grouping_shared_constants.h"

namespace grouping_shared {

const grouping_sharedConstants g_grouping_shared_constants;

grouping_sharedConstants::grouping_sharedConstants() {
}

} // namespace

