/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef grouping_shared_CONSTANTS_H
#define grouping_shared_CONSTANTS_H

#include "grouping_shared_types.h"

namespace grouping_shared {

class grouping_sharedConstants {
 public:
  grouping_sharedConstants();

};

extern const grouping_sharedConstants g_grouping_shared_constants;

} // namespace

#endif
